### ISSUE TITLE
Configuration Button Shuts crashes 2.1

### ISSUE THREAD

**Issue by sombody88** [pvdstel/DuckyProfileSwitcher#1]
When pressing the "configuration" botton. The app crashes. 

These are fresh install. 

Not sure if there are other windows requirements. Official autoprofiler works without any issues.

**Comment by pvdstel** [comment]
Hi! Thanks for reporting this issue!

There isn't much I can do without knowing what the error is. I've created a new release, [version 0.3.0](https://github.com/pvdstel/DuckyProfileSwitcher/releases/tag/v0.3.0). Could you try that one and see if it still crashes? That version includes a fail-safe, it should let you know if something fails.

**Comment by sombody88** [comment]
Just tried 3.0 out... had the system error message saying no application to open the config.json file. At least now, the program does not crash and someone gets the error message.

I was able to fix it by setting a default app for the json file. After setting a default app, everything works smoothly.
